# Generated by Django 2.2.16 on 2020-10-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('newsletter', '0005_auto_20190918_0122'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='SubmissionSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'newsletter_submission_subscriptions',
                'verbose_name': 'Subscription Submission',
                'verbose_name_plural': 'Subscription Submissions',
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='subscriptions',
            field=models.ManyToManyField(
                blank=True, db_index=True,
                help_text='If you select none, the system will automatically find the subscribers for you.',
                through='newsletter.SubmissionSubscriptions',
                to='newsletter.Subscription', verbose_name='recipients'
            ),
        ),
        migrations.AddField(
            model_name='submissionsubscriptions',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newsletter.Submission'),
        ),
        migrations.AddField(
            model_name='submissionsubscriptions',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newsletter.Subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionsubscriptions',
            unique_together={('submission', 'subscription')},
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name='submissionsubscriptions',
            name='status',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
